---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/available_puppies":
    get:
      summary: Fetch the available puppies
      tags:
      - Retrieves all available Puppies
      parameters:
      - name: puppy
        in: query
        properties:
          name:
            type: string
          date_of_birth:
            type: date
          picture:
            type: string
          weight:
            type: integer
          description:
            type: string
          gender:
            type: string
          father:
            type: string
          mother:
            type: string
          wolf_percentage:
            type: integer
          availability:
            type: boolean
        required:
        - name
        - date_of_birth
        - picture
        - weight
        - description
        - gender
        - father
        - mother
        - wolf_percentage
        - availability
        schema:
          type: object
      responses:
        '200':
          description: puppies fetched
    post:
      summary: Creates a puppy
      tags:
      - Creates a puppy
      parameters: []
      responses:
        '201':
          description: puppy created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                date_of_birth:
                  type: date
                picture:
                  type: string
                weight:
                  type: integer
                description:
                  type: string
                gender:
                  type: string
                father:
                  type: string
                mother:
                  type: string
                wolf_percentage:
                  type: integer
                availability:
                  type: boolean
              required:
              - name
              - date_of_birth
              - picture
              - weight
              - description
              - gender
              - father
              - mother
              - wolf_percentage
              - availability
  "/available_puppies/{id}":
    get:
      summary: Retrieves a puppy
      tags:
      - Retrieves a puppy
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: puppy found
        '404':
          description: puppy not found
        '406':
          description: unsupported accept header
    put:
      summary: Updates a puppy
      tags:
      - Updates a puppy
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: puppy updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                date_of_birth:
                  type: date
                picture:
                  type: string
                weight:
                  type: integer
                description:
                  type: string
                gender:
                  type: string
                father:
                  type: string
                mother:
                  type: string
                wolf_percentage:
                  type: integer
                availability:
                  type: boolean
    delete:
      summary: Deletes a puppy
      tags:
      - Deletes a puppy
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: puppy deleted
  "/female_wolves":
    post:
      summary: Creates a female wolf
      tags:
      - Creates a female wolf
      parameters: []
      responses:
        '201':
          description: Male wolf created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                date_of_birth:
                  type: date
                picture:
                  type: string
                weight:
                  type: integer
                description:
                  type: string
                wolf_percentage:
                  type: integer
              required:
              - name
              - date_of_birth
              - picture
              - weight
              - description
              - wolf_percentage
    get:
      summary: Fetch the female wolves
      tags:
      - Retrieves all female wolves
      parameters:
      - name: femaleWolf
        in: query
        properties:
          name:
            type: string
          date_of_birth:
            type: date
          picture:
            type: string
          weight:
            type: integer
          description:
            type: string
          wolf_percentage:
            type: integer
        required:
        - name
        - date_of_birth
        - picture
        - weight
        - description
        - wolf_percentage
        schema:
          type: object
      responses:
        '200':
          description: male wolves fetched
  "/female_wolves/{id}":
    get:
      summary: Retrieves a female wolf
      tags:
      - Retrieves a female wolf
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: female wolf found
    put:
      summary: Updates a female wolf
      tags:
      - Updates a female wolf
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: female updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                date_of_birth:
                  type: date
                picture:
                  type: string
                weight:
                  type: integer
                description:
                  type: string
                wolf_percentage:
                  type: integer
    delete:
      summary: Deletes a female wolf
      tags:
      - Deletes female wolf
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: female deleted
        '404':
          description: female wolf not found
        '406':
          description: unsupported accept header
  "/male_wolves":
    post:
      summary: Creates a male wolf
      tags:
      - Creates a male wolf
      parameters: []
      responses:
        '201':
          description: Male wolf created
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                date_of_birth:
                  type: date
                picture:
                  type: string
                weight:
                  type: integer
                description:
                  type: string
                wolf_percentage:
                  type: integer
              required:
              - name
              - date_of_birth
              - picture
              - weight
              - description
              - wolf_percentage
    get:
      summary: Fetch the male wolves
      tags:
      - Retrieves all male wolves
      parameters:
      - name: maleWolf
        in: query
        properties:
          name:
            type: string
          date_of_birth:
            type: date
          picture:
            type: string
          weight:
            type: integer
          description:
            type: string
          wolf_percentage:
            type: integer
        required:
        - name
        - date_of_birth
        - picture
        - weight
        - description
        - wolf_percentage
        schema:
          type: object
      responses:
        '200':
          description: male wolves fetched
  "/male_wolves/{id}":
    get:
      summary: Retrieves a male wolf
      tags:
      - Retrieves a male wolf
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: male wolf found
    put:
      summary: Updates a male wolf
      tags:
      - Updates a male wolf
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Male updated
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                date_of_birth:
                  type: date
                picture:
                  type: string
                weight:
                  type: integer
                description:
                  type: string
                wolf_percentage:
                  type: integer
    delete:
      summary: Deletes a male wolf
      tags:
      - Deletes Male wolf
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: Male deleted
        '404':
          description: male wolf not found
        '406':
          description: unsupported accept header
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
